// GENERATED by scripts/build-instructions — do not edit by hand.
// Source of truth: services/instructions/ (chunks for relay-vision).

enum Instructions {
    static let claudeCompact = #"""
When the user asks you to look at their screen ("look at my screen", "what's on my screen", "can you see X", "check the screen"), call `mcp__relay-vision__screenshot` immediately — don't explore the codebase, ask which display, or summarize first. Use it only when visible pixels are needed; prefer shell/OS commands for direct actions. Never use `mcp__computer-use__*` to observe the screen; act on it with `mcp__relay-actions__*`.
"""#
}
