// GENERATED by scripts/build-instructions — do not edit by hand.
// Source of truth: services/instructions/ (chunks for relay-orchestrator).

enum Instructions {
    static let payload = #"""
## The orchestration workflow

When the relay-orchestrator MCP is connected, you are the **orchestrator**, not the executor. Tickets live in the repo's `.orchestrator/` directory — that's the source of truth. No external service. **The board is gated on an active `/relay-bridge` session** — the bridge's launching cwd is what tells the menu-bar app which repo's `.orchestrator/` to render, so without a live bridge (`/tmp/voice_bridge.sock` present) the board hotkey just surfaces the same "No session running" pill the record-out-of-session path uses. **The `ready` column is the auto-dispatch trigger**: any ticket the board UI moves into `ready` (drag, or new-in-ready + save) fires `dispatch_ticket` immediately. Dependency progression auto-advances dependents (`backlog→ready`) when a predecessor lands in `done`. The four steps:

1. **Discuss.** Talk through the work. Surface assumptions, push back, propose alternatives — think before coding.
2. **Write tickets in `backlog`.** When the discussion settles on concrete work, write a ticket file under `<repo>/.orchestrator/<TICKET_ID>.md` following the schema in `docs/specs/orchestrator-tickets.md`. Use the next free id from `.orchestrator/config.toml` (`next_id`) and bump that counter in the same commit. Default `status: backlog`. Each ticket needs a title, a `## Description`, `## Acceptance criteria` a sub-agent can verify against, a priority, and `depends_on` if it needs another ticket to land first. Keep them small and standalone — a sub-agent has no memory of the discussion. Commit the new ticket on the working branch.
3. **Refine and promote.** When a ticket is concrete enough that you'd hand it to a colleague cold, drag it from `backlog` to `ready` in the board (or change the frontmatter to `status: ready` and save via the editor). The board immediately calls `dispatch_ticket(ticket_id, repo_path)`; a worker spawns in an isolated worktree. The first ticket of a chain is the only one you drag — its `depends_on` predecessors auto-promote when each one completes. For a one-off manual dispatch (e.g. retry, skip the queue), the MCP tool `mcp__relay-orchestrator__dispatch_ticket` still works directly. Use `context="..."` when the ticket body wouldn't survive cold without this conversation.
4. **Integrate.** Each sub-agent commits to its `relay/<id>` branch — both the code change and the ticket-file update (status flipped to `done` + a `## Run log` entry). Merge those branches into the working branch in a sensible order, resolve conflicts intentionally (don't just accept "theirs"), then prune worktrees + delete the throwaway branches. The merge is what publishes the `done` status to the board, which is what triggers any dependents waiting on this ticket to flip to `ready` and dispatch in turn.

A small change you can do inline in this session **without going through the board** is fine — dispatching has cold-start cost, eats agent quota, and offers no coordination. Promote to `ready` when the work is large enough that the round-trip pays off, or when you want an in-repo audit trail (ticket + run log) without writing it by hand.

### Things to avoid

- Don't drag tickets to `ready` casually — promotion equals dispatch. Refine first.
- Don't push `relay/<id>` branches. They're throwaway by design; integrate into the working branch (typically `main`) before deleting.
- Don't let a sub-agent edit `.orchestrator/` files other than its own ticket. That boundary is enforced in `services/orchestrator_workflow.md`. The daemon writes ticket files in exactly one case: flipping a dependent from `backlog` to `ready` after its predecessor finishes.
- Don't ad-hoc fix the bundled `.app`'s scripts. The DMG-build action is the source of truth; commit fixes upstream and let the action rebuild.

## Recovery patterns

- **Codex worker fails with an authentication error.** Open a Terminal window with `codex login` running, wait for the user to finish sign-in, then re-dispatch the failed runs:

  ```bash
  osascript -e 'tell application "Terminal" to activate' \
            -e 'tell application "Terminal" to do script "codex login"'
  ```

  After sign-in completes (heuristic: `~/.codex/auth.json` exists and is fresh), re-dispatch via `mcp__relay-orchestrator__dispatch_ticket` for each failed run.

- **Claude worker fails with `401 Invalid authentication credentials`.** If the repo is explicitly configured to use Claude, open a Terminal window with `claude /login`, wait for the user to complete OAuth, then re-dispatch the failed runs:

  ```bash
  osascript -e 'tell application "Terminal" to activate' \
            -e 'tell application "Terminal" to do script "claude /login"'
  ```

## Naming notes

- **Relay Actions** = the screen-*manipulation* feature and its MCP tool family (`mcp__relay-actions__*`): click, type, scroll, key, list_windows, frontmost_app.
- **Relay Vision** = the screen-*observation* feature and its MCP tool family (`mcp__relay-vision__*`): screenshot (initially). Split out of Relay Actions in RR-10.
- **ActionGlow** = the perimeter-glow overlay that pulses whenever a RelayActions *or* RelayVision tool runs. It is automatic — driven by the `tool_fired` notification every RelayActions and RelayVision tool sends after running — so you never call it directly. It is a **visual signal**, not a confirmation gate. (`OverlayState.actionGlow` in code.)
- Together: **the Relay stack**. Don't conflate any of these with native "computer-use" or "computer-vision" — those are different MCPs from a different vendor.
"""#
}
